### ISSUE TITLE
Plugin legacy name certbot-loopia:auth may be removed in a future version. Please use auth instead.

### ISSUE THREAD

**Issue by CraXyOW3** [runfalk/certbot-loopia#10]
So Python 2 is nearing EOL :/
Thus i now installed Python 3 and made a fresh install of certbot and also this sweet certbot plugin! :D

But now i am greeted by "Plugin legacy name certbot-loopia:auth may be removed in a future version. Please use auth instead.".
Is there a possibility that you will update your plugin for this?

Thanks !

**Comment by runfalk** [comment]
Well, Python 2 has been dead since April. :smile: 

I will probably update this plugin since it pretty much shares its core with https://github.com/runfalk/certbot-glesys (which I do maintain). It should be the same fix. However, I don't plan on doing it any time soon. I'd expect this version to continue working for a quite some time, and if it stops working you can pin your certbot version to a working one.

**Comment by runfalk** [comment]
So I did end up fixing this in my glesys plugin: https://github.com/runfalk/certbot-dns-glesys/commit/900809ecded2060e0254ec98eda7841232ee69e3

If anyone wants to have a go at implementing this as a PR I'll merge it. The main change is that the arguments and parameters in the ini no longer requires the prefix `certbot-loopia:` and that the entry point in `setup.py` should be changed from `auth` to `dns-loopia`. The name should also be changed to `certbot-dns-loopia`.
