### ISSUE TITLE
documentation: Permissions for Loopia API user

### ISSUE THREAD

**Issue by KufrA** [runfalk/certbot-loopia#6]
Using this plugin for certbot and seems to work perfectly.

Had some issues figuring out what permissions i was supposed to use for the Loopia API user.
Think in the end i added all the Subdomain and all the record (Create/delete/read) permssions.

If possible, add to readme the exact permissions being used by the script.

Also, thanks for publishing your work!

**Comment by runfalk** [comment]
Since I am no longer a Loopia customer, I can't actually check how the permission system works. Here are the methods certbot-loopia calls:

- getZoneRecords
- addZoneRecord
- removeZoneRecord
- removeSubdomain

This may be required but I am not sure:

- addSubdomain (It doesn't explicitly call this, but addZoneRecord will implicitly create a sub domain)

It would be great if you could check the exact permission names and reply here. If you do I can update the README.

**Comment by KufrA** [comment]
Current permissions that i use:
- addSubdomain (maybe)
- addZoneRecord
- getSubdomains (probably not needed)
- getZoneRecords
- removeSubdomain
- removeZoneRecord
- updateZoneRecord (probably not needed)

Think add/remove subdomain is needed. It failed when i only added the three ZoneRecord options. But did not try them individually. I'm not super confident in my ways of testing this so might aswell leave this comment here for others to read.

**Comment by runfalk** [comment]
I updated the README to reflect the new permissions.
